### ISSUE TITLE
Gallery app erroring

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny-templates#26]
https://gallery.shinyapps.io/template-stock-app/

Is generating this error:
![Image](https://github.com/user-attachments/assets/80764045-69d4-46f2-8eef-104afff50dd4)

**Comment by cpsievert** [comment]
Thanks for reporting. It looks as though cufflinks is straight up broken with recent versions of pandas, and the repo hasn't seen any activity in years, so I think, unfortunately, the best move here is to pin the version of pandas.
